version: '3'

services:

  mysql_database:
    image: mysql:8.0.15
    restart: always
    environment:
      MYSQL_DATABASE: acciom_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: acciom_user
      MYSQL_PASSWORD: acciom_password
    expose:
      - "3307"
    ports:
      - "3307:3306"
    volumes:
      - my-datavolume:/var/lib/mysql

  flask_web:
    container_name: flask_web
    restart: always
    depends_on:
      - mysql_database
    build: .
    command: >
      bash -c "export PYSPARK_PYTHON=/usr/bin/python3 &&
      export LC_ALL=C.UTF-8 &&
      export LANG=C.UTF-8 &&
      export FLASK_APP=manage.py &&
      flask db upgrade &&
      gunicorn --bind 0.0.0.0:7000 --workers 3 --reload app:app"
    volumes:
      - .:/acciom
    ports:
      - "7000:7000"

volumes:
  my-datavolume: