FROM ubuntu:18.04

# Install Package
RUN apt-get update
RUN apt-get install -y software-properties-common vim curl gcc wget
RUN apt-get install -y build-essential python3-dev python3-pip
RUN apt-get install -y mysql-client unixodbc-dev
RUN apt-get install -y openjdk-8-jdk

# update pip
RUN python3 -m pip install pip --upgrade

# Install Spark
RUN wget http://apachemirror.wuchna.com/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz
RUN tar xvf spark-2.4.3-bin-hadoop2.7.tgz
RUN mv spark-2.4.3-bin-hadoop2.7 /usr/local/
RUN rm spark-2.4.3-bin-hadoop2.7.tgz
RUN ln -s /usr/local/spark-2.4.3-bin-hadoop2.7/ /usr/local/spark
ENV SPARK_HOME="/usr/local/spark"
ENV PYSPARK_PYTHON="/usr/bin/python3"
ENV PYTHONUNBUFFERED 1
RUN python3 -m pip install pyspark==2.4.3
