version: '3.7'

services:

  mysql_database:
    image: mysql:8.0.15
    restart: always
    environment:
      MYSQL_DATABASE: Acciom_tool
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: Acciom_user
      MYSQL_PASSWORD: Acciompass
    ports:
      - "3306:3306"
    volumes:
      - my-datavolume:/var/lib/mysql

  flask_web:
    container_name: flask_web
    depends_on:
      - mysql_database
    build: .
    command: >
      bash -c "python3 app.py"
    volumes:
      - .:/acciom
    ports:
      - "5000:5000"

volumes:
  my-datavolume: