"""empty message

Revision ID: 047e0027435a
Revises: 
Create Date: 2019-03-04 18:22:24.167213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '047e0027435a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=280), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dbdetail',
    sa.Column('db_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('db_type', sa.String(length=80), nullable=False),
    sa.Column('db_name', sa.String(length=80), nullable=False),
    sa.Column('db_hostname', sa.String(length=80), nullable=False),
    sa.Column('db_username', sa.String(length=80), nullable=False),
    sa.Column('db_password', sa.String(length=80), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('db_id')
    )
    op.create_table('test_suite',
    sa.Column('test_suite_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('excel_name', sa.String(length=300), nullable=False),
    sa.Column('test_suite_name', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('test_suite_id')
    )
    op.create_table('test_case',
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('test_suite_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.String(length=80), nullable=True),
    sa.Column('test_status', sa.Integer(), nullable=True),
    sa.Column('test_priority', sa.String(length=80), nullable=True),
    sa.Column('test_detail', sa.Text(), nullable=True),
    sa.Column('test_column', sa.Text(), nullable=True),
    sa.Column('table_src_target', sa.Text(), nullable=True),
    sa.Column('test_name', sa.String(length=80), nullable=True),
    sa.Column('test_queries', sa.Text(), nullable=True),
    sa.Column('test_expected', sa.Text(), nullable=True),
    sa.Column('test_actual', sa.Text(), nullable=True),
    sa.Column('test_created_by', sa.String(length=80), nullable=True),
    sa.Column('test_executed_by', sa.String(length=80), nullable=True),
    sa.Column('test_comment', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suite.test_suite_id'], ),
    sa.PrimaryKeyConstraint('test_case_id')
    )
    op.create_table('test_case_log',
    sa.Column('test_case_log_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('execution_status', sa.Integer(), nullable=True),
    sa.Column('src_execution_log', mysql.LONGTEXT(), nullable=True),
    sa.Column('des_execution_log', mysql.LONGTEXT(), nullable=True),
    sa.Column('error_log', sa.String(length=80), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.test_case_id'], ),
    sa.PrimaryKeyConstraint('test_case_log_id')
    )
    op.create_table('sparkjob',
    sa.Column('spark_job_id', sa.Integer(), nullable=False),
    sa.Column('test_case_log_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_log_id'], ['test_case_log.test_case_log_id'], ),
    sa.PrimaryKeyConstraint('spark_job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sparkjob')
    op.drop_table('test_case_log')
    op.drop_table('test_case')
    op.drop_table('test_suite')
    op.drop_table('dbdetail')
    op.drop_table('user')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
