"""empty message

Revision ID: 0553d3d04d93
Revises: beab586373e9
Create Date: 2019-03-28 15:37:35.752959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0553d3d04d93'
down_revision = 'beab586373e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbdetail',
    sa.Column('db_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('db_type', sa.String(length=80), nullable=False),
    sa.Column('db_name', sa.String(length=80), nullable=False),
    sa.Column('db_hostname', sa.String(length=80), nullable=False),
    sa.Column('db_username', sa.String(length=80), nullable=False),
    sa.Column('db_password', sa.String(length=80), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'db_type', 'db_name', 'db_hostname', 'db_username'),
    sa.UniqueConstraint('db_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbdetail')
    # ### end Alembic commands ###
