"""empty message

Revision ID: 111eaa5da00b
Revises: c61fcb938b23
Create Date: 2019-04-04 16:24:13.645280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '111eaa5da00b'
down_revision = 'c61fcb938b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case', 'test_detail')
    op.drop_column('test_case', 'test_comment')
    op.drop_column('test_case', 'test_created_by')
    op.drop_column('test_case', 'test_executed_by')
    op.drop_column('test_case', 'test_actual')
    op.drop_column('test_case', 'test_priority')
    op.drop_column('test_case', 'test_expected')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('test_expected', mysql.TEXT(), nullable=True))
    op.add_column('test_case', sa.Column('test_priority', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('test_case', sa.Column('test_actual', mysql.TEXT(), nullable=True))
    op.add_column('test_case', sa.Column('test_executed_by', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('test_case', sa.Column('test_created_by', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('test_case', sa.Column('test_comment', mysql.TEXT(), nullable=True))
    op.add_column('test_case', sa.Column('test_detail', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
