"""empty message

Revision ID: 200631e5b6a8
Revises: 0553d3d04d93
Create Date: 2019-03-28 23:08:41.321182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '200631e5b6a8'
down_revision = '0553d3d04d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dbdetail_db_id'), 'dbdetail', ['db_id'], unique=True)
    op.drop_index('db_id', table_name='dbdetail')
    op.add_column('test_case', sa.Column('src_connection_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.add_column('test_case', sa.Column('target_connection_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'test_case', 'dbdetail', ['src_connection_id'], ['db_id'])
    op.create_foreign_key(None, 'test_case', 'dbdetail', ['target_connection_id'], ['db_id'])
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index('email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.drop_column('test_case', 'target_connection_id')
    op.drop_column('test_case', 'src_connection_id')
    op.create_index('db_id', 'dbdetail', ['db_id'], unique=True)
    op.drop_index(op.f('ix_dbdetail_db_id'), table_name='dbdetail')
    # ### end Alembic commands ###
