"""empty message

Revision ID: 60bf56cfdee8
Revises: 200631e5b6a8
Create Date: 2019-03-28 23:19:06.135196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bf56cfdee8'
down_revision = '200631e5b6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'test_case', 'dbdetail', ['src_connection_id'], ['db_id'])
    op.create_foreign_key(None, 'test_case', 'dbdetail', ['target_connection_id'], ['db_id'])
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index('email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    # ### end Alembic commands ###
