"""empty message

Revision ID: fc415bca3509
Revises: 96b391e9f135
Create Date: 2019-03-28 23:30:50.561630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc415bca3509'
down_revision = '96b391e9f135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('src_db_id', sa.Integer(), nullable=True))
    op.add_column('test_case', sa.Column('target_db_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_case', 'dbdetail', ['src_db_id'], ['db_id'])
    op.create_foreign_key(None, 'test_case', 'dbdetail', ['target_db_id'], ['db_id'])
    op.drop_column('test_case', 'target_connection_id')
    op.drop_column('test_case', 'src_connection_id')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index('email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.add_column('test_case', sa.Column('src_connection_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True))
    op.add_column('test_case', sa.Column('target_connection_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.drop_column('test_case', 'target_db_id')
    op.drop_column('test_case', 'src_db_id')
    # ### end Alembic commands ###
