"""empty message

Revision ID: fcce7fc43ace
Revises: 
Create Date: 2019-04-08 11:49:28.219742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcce7fc43ace'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=280), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('dbdetail',
    sa.Column('db_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connection_name', sa.String(length=80), nullable=True),
    sa.Column('db_type', sa.String(length=80), nullable=False),
    sa.Column('db_name', sa.String(length=80), nullable=False),
    sa.Column('db_hostname', sa.String(length=80), nullable=False),
    sa.Column('db_username', sa.String(length=80), nullable=False),
    sa.Column('db_password', sa.String(length=80), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('db_id')
    )
    op.create_table('test_suite',
    sa.Column('test_suite_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('excel_name', sa.String(length=300), nullable=False),
    sa.Column('test_suite_name', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('test_suite_id')
    )
    op.create_table('test_case',
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('test_suite_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.String(length=80), nullable=True),
    sa.Column('test_status', sa.Integer(), nullable=True),
    sa.Column('test_column', sa.Text(), nullable=True),
    sa.Column('table_src_target', sa.Text(), nullable=True),
    sa.Column('test_name', sa.String(length=80), nullable=True),
    sa.Column('test_queries', sa.Text(), nullable=True),
    sa.Column('src_db_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('target_db_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['src_db_id'], ['dbdetail.db_id'], ),
    sa.ForeignKeyConstraint(['target_db_id'], ['dbdetail.db_id'], ),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suite.test_suite_id'], ),
    sa.PrimaryKeyConstraint('test_case_id')
    )
    op.create_table('test_case_log',
    sa.Column('test_case_log_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('execution_status', sa.Integer(), nullable=True),
    sa.Column('src_execution_log', mysql.LONGTEXT(), nullable=True),
    sa.Column('des_execution_log', mysql.LONGTEXT(), nullable=True),
    sa.Column('error_log', sa.String(length=80), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.test_case_id'], ),
    sa.PrimaryKeyConstraint('test_case_log_id')
    )
    op.create_table('sparkjob',
    sa.Column('spark_job_id', sa.Integer(), nullable=False),
    sa.Column('test_case_log_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_log_id'], ['test_case_log.test_case_log_id'], ),
    sa.PrimaryKeyConstraint('spark_job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sparkjob')
    op.drop_table('test_case_log')
    op.drop_table('test_case')
    op.drop_table('test_suite')
    op.drop_table('dbdetail')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
